name: tfm-nnUnet
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0=mkl
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - expat=2.7.3=h885b0b7_4
  - filelock=3.20.0=py310haa95532_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py310h8598115_0
  - idna=3.11=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py310haa95532_0
  - jpeg=9f=ha349fce_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py310h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - numpy=2.0.1=py310h055cbcc_1
  - numpy-base=2.0.1=py310h65a83cf_1
  - opencl-headers=2025.07.22=h885b0b7_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.3=pyhc872135_0
  - pycparser=2.23=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py310hb9a58be_0
  - requests=2.32.5=py310haa95532_1
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.14.0=py310haa95532_1
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - typing_extensions=4.15.0=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.0=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - acvl-utils==0.2.5
      - anyio==4.12.0
      - argparse==1.4.0
      - asttokens==3.0.1
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - blosc2==3.12.2
      - click==8.3.1
      - colorama==0.4.6
      - connected-components-3d==3.26.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - dynamic-network-architectures==0.4.2
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fft-conv-pytorch==1.2.0
      - fonttools==4.61.0
      - fsspec==2025.12.0
      - future==1.0.0
      - graphviz==0.21
      - h11==0.16.0
      - hf-xet==1.2.0
      - hiddenlayer==0.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.1
      - imagecodecs==2025.3.30
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - ipython==8.37.0
      - jedi==0.19.2
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - linecache2==1.0.0
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - msgpack==1.1.2
      - ndindex==1.10.1
      - nibabel==5.3.3
      - nnunetv2==2.6.2
      - numexpr==2.14.1
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - shellingham==1.5.4
      - simpleitk==2.5.3
      - six==1.17.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - torch==2.9.1+cu128
      - torchaudio==2.9.1+cu128
      - torchvision==0.24.1+cu128
      - tqdm==4.67.1
      - traceback2==1.4.0
      - traitlets==5.14.3
      - typer-slim==0.20.0
      - tzdata==2025.2
      - unittest2==1.1.0
      - wcwidth==0.2.14
      - yacs==0.1.8
prefix: C:\Users\reyes\anaconda3\envs\tfm-nnUnet
