name: tfm-lab2im
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - ca-certificates=2025.11.4=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.18=h543e019_0
  - pip=24.2=py38haa95532_0
  - python=3.8.20=h8205438_0
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==5.5.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - flatbuffers==25.9.23
      - gast==0.4.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - keras==2.13.1
      - lab2im==1.0
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==2.1.5
      - nibabel==5.2.1
      - numpy==1.24.3
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - packaging==25.0
      - pillow==10.4.0
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scipy==1.10.1
      - six==1.17.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - typing-extensions==4.5.0
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - wrapt==2.0.1
      - zipp==3.20.2
prefix: C:\Users\reyes\anaconda3\envs\tfm-lab2im
