name: tfm-analitycs
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.10.0=py310haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310h02ab6af_0
  - asttokens=3.0.0=py310haa95532_0
  - async-lru=2.0.5=py310haa95532_0
  - attrs=25.4.0=py310haa95532_2
  - babel=2.17.0=py310haa95532_0
  - beautifulsoup4=4.14.2=py310haa95532_0
  - bleach=6.3.0=py310haa95532_0
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.3=py310haa95532_0
  - cudatoolkit=11.2.2=h7d7167e_13
  - cudnn=8.1.0.77=h3e0f4f4_0
  - debugpy=1.8.16=py310h885b0b7_1
  - decorator=5.2.1=py310haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - expat=2.7.3=h885b0b7_4
  - h11=0.16.0=py310haa95532_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py310haa95532_0
  - httpx=0.28.1=py310haa95532_1
  - idna=3.11=py310haa95532_0
  - ipykernel=6.31.0=py310h4442805_0
  - ipython=8.30.0=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.6=py310haa95532_0
  - json5=0.12.1=py310haa95532_0
  - jsonschema=4.25.0=py310haa95532_1
  - jsonschema-specifications=2025.9.1=py310haa95532_0
  - jupyter-lsp=2.2.5=py310haa95532_0
  - jupyter_client=8.6.3=py310haa95532_1
  - jupyter_core=5.9.1=py310haa95532_0
  - jupyter_events=0.12.0=py310haa95532_0
  - jupyter_server=2.17.0=py310haa95532_0
  - jupyter_server_terminals=0.5.3=py310haa95532_0
  - jupyterlab=4.5.0=py310haa95532_0
  - jupyterlab_pygments=0.3.0=py310haa95532_0
  - jupyterlab_server=2.28.0=py310haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=py310haa95532_0
  - mistune=3.1.2=py310haa95532_0
  - nbclient=0.10.2=py310haa95532_0
  - nbconvert-core=7.16.6=py310haa95532_0
  - nbformat=5.10.4=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - notebook=7.5.0=py310haa95532_0
  - notebook-shim=0.2.4=py310haa95532_0
  - openssl=3.6.0=h725018a_0
  - overrides=7.7.0=py310haa95532_0
  - packaging=25.0=py310haa95532_1
  - pandocfilters=1.5.1=py310haa95532_0
  - parso=0.8.5=py310haa95532_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py310haa95532_0
  - prometheus_client=0.21.1=py310haa95532_0
  - prompt-toolkit=3.0.52=py310haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py310h02ab6af_1
  - pure_eval=0.2.3=py310haa95532_0
  - pycparser=2.23=py310haa95532_0
  - pygments=2.19.2=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-fastjsonschema=2.21.2=py310haa95532_0
  - python-json-logger=4.0.0=py310haa95532_0
  - pywin32=311=py310h885b0b7_0
  - pywinpty=2.0.15=py310h72d21ff_0
  - pyyaml=6.0.3=py310hb9a58be_0
  - pyzmq=27.1.0=py310h7149c55_1
  - referencing=0.37.0=py310haa95532_0
  - requests=2.32.5=py310haa95532_1
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rpds-py=0.28.0=py310h114bc41_0
  - send2trash=1.8.2=py310haa95532_1
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sniffio=1.3.1=py310haa95532_0
  - soupsieve=2.5=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py310haa95532_0
  - terminado=0.18.1=py310haa95532_0
  - tinycss2=1.4.0=py310haa95532_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py310haa95532_0
  - tornado=6.5.1=py310h827c3e9_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py310haa95532_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=1.8.0=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==6.2.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.61.0
      - gast==0.4.0
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - nibabel==5.3.3
      - numpy==1.23.5
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - pathlib==1.0.1
      - pillow==12.0.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.5
      - pytz==2025.2
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-addons==0.22.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typeguard==2.13.3
      - tzdata==2025.2
      - urllib3==2.6.1
      - werkzeug==3.1.4
      - wrapt==2.0.1
prefix: C:\Users\reyes\anaconda3\envs\tfm-analitycs
